13-Listagem da equipe e descrição do projeto na home
fga-eps-mds/2022-2-CAPJu-Doc pull request #15
Opened 2022-11-14 16:51 UTC by LucasLopesFrazao

## Critérios de Aceitação
- [ ] Seção com descrição do projeto.
- [ ] Seção com os membros de EPS.
- [ ] Seção com os membros de MDS.
- [ ] Pagina deve conter seção de referências(Se necessário).
- [ ] Pagina deve conter seção de versionamento.

resolve #13

2022-11-14 17:57 UTC, AntonioAldisio reviewed
Boa tarde, os dois comentarios que fiz sobre a imagem e o link é aplicavel ao outros membros e tbm é interessante colocar em ordem alfabética

2022-11-14 17:57 UTC, AntonioAldisio commented on pages/home.md
> +O CAPJu (Controle e Acompanhamento de Processos da Justiça), trata-se de um sistema Web criado por alunos da UnB - Gama com o propósito de auxiliar usuários a gerenciar fluxos de processos da justiça
Subistituir :
criado por alunos da UnB - Gama
Por:
desenvolvido pelos alunos do curso de Engenharia de Software da Faculdade na Universidade de Brasília (UnB).

2022-11-14 17:57 UTC, AntonioAldisio commented on pages/home.md
> +      <img class="borda" src="https://avatars.githubusercontent.com/u/71859307?v=4"/>
recomendo trocar a url por https://github.com/ilus1.png. Isso evita que se o usuario troca de imagem a quebra da imagem

2022-11-14 17:57 UTC, AntonioAldisio commented on pages/home.md
> +    <label>Fernando Miranda</label>
fazer em formato de link [Fernando Miranda](https://github.com/ilus1)

2022-11-14 18:32 UTC, LucasLopesFrazao commented on pages/home.md
> +    <label>Fernando Miranda</label>
Não foi possível utilizar o formato de link do markdown dentro de uma tag do HTML, ficou totalmente quebrado: 

![image](https://user-images.githubusercontent.com/89523373/201738152-5e50a047-9d2a-4d03-a35e-744251c842ea.png)

Minha solução foi fazer um tag <a> que envolve-se a foto de cada componente e no href colocar o link do github, funcionamento como esperado.

2022-11-14 19:07 UTC, AntonioAldisio commented on pages/home.md
> +    <label>Fernando Miranda</label>
Tudo bem. Nao vi que estava dentro de uma tag html para a tag precisa usar href desse modelo.
Exemplo 
<a href="https://github.com/DaviAntonio">
      <div class="foto">
        <img class="borda" src="https://github.com/DaviAntonio.png"/>
      </div>  
    </a>
    <label><a href="https://github.com/DaviAntonio">Davi Antonio</a></label>
  </div>

2022-11-14 19:52 UTC, LucasLopesFrazao commented
@AntonioAldisio finalizei as correções solicitadas.

2022-11-14 21:41 UTC, ilus1 requested changes

2022-11-14 21:41 UTC, ilus1 commented on assets/css/custom.css
> +.container {
Nome ta muito genérico, vc precida identificar onde vc vai por isso com o nome, algo como profilePictureList ou algo parecido pode ser uma boa

2022-11-14 21:41 UTC, ilus1 commented on pages/home.md
> +  </div>
- Aqui não é necessário uma dix pra conter o item todo, vc pode usar a tag <a>, já que o link vai ser a imagem toda.
- No Html 5, é uma boa pratica vc usar a tag <figure> pra colocar uma imagem.
- É boa pratica sempre adicionar o atributo alt da figure/image
- A label pode ser substituida pela <figcaption> pelo mesmo motivo

um exemplo de como ficaria:

```
  <a href="https://github.com/antonioaldisio">
    <figure class="item">
      <img class="foto" src="https://github.com/antonioaldisio.png" alt="Foto do Antônio"/>
      <figcaption>Antônio aldisio</figcaption>
    </figure>
  </a>
```

2022-11-14 21:41 UTC, ilus1 commented on assets/css/custom.css
> +.foto {
- Tamanho: é bom sempre que você for por tamanho em alguma coisa usar as [unidades](https://www.w3schools.com/cssref/css_units.php) relativas(em, rem, vw....). Nesse caso eu recomendo 10vw. Onde o vw vai ser relativo ao tamanho da tela.
- Borda: é bom por ela direto na imagem, que a imagem tbm ganha os cantos arredondados, e encaixa melhor com a borda

2022-11-14 21:41 UTC, ilus1 commented on assets/css/custom.css
> +}
- Só poe um pading nessa imagem pra retirar/centralizar esse espaço em branco na borda, vou ter um infarto aqui.
![image](https://user-images.githubusercontent.com/71859307/201771012-383f5a6f-836f-42c5-864c-a179d63d5661.png)

2022-11-14 21:41 UTC, ilus1 commented on assets/css/custom.css
> +.item label {
Posso até estar enganado, mas o fato de ter um espaço faz o css tratar isso como uma extenção da classe item, entao é bom vc usar um padrão que não tenha espaço, eu recomendo camelCase.
ex: .itemLabel

PS: Os nomes sempre devem descrever qual parte do sistema eles vao alterar (nomes significativos)

2022-11-15 17:59 UTC, LucasLopesFrazao commented
@ilus1 @AntonioAldisio alterações solicitadas foram realizadas.

2022-11-15 19:35 UTC, AntonioAldisio approved these changes

2022-11-15 22:23 UTC, ilus1 requested changes

2022-11-15 22:23 UTC, ilus1 commented on assets/css/custom.css
> +.HomeMembroItem {
- Membro da em portugues enquanto o resto do nome ta em ingles
- Esse item ta meio generico ainda, troca pra Profile, fica melhor

2022-11-16 00:35 UTC, ilus1 approved these changes
:+1:

2022-11-16 00:36 UTC, merged