Docs/5 disponibilidade
fga-eps-mds/2022-2-CAPJu-Doc pull request #16
Opened 2022-11-14 21:25 UTC by SamuelGSouza

Criado a documentação de registro de disponibilidade. 
Resolve#5

2022-11-14 23:12 UTC, AntonioAldisio commented on pages/team_control/time.md
> +| 11/11/2022 | 0.1    | Criação do plano de organização de tempo da equipe               | Samuel G. / Henrique P.   |
Por favor, colocar no padrao 0.0.0

2022-11-14 23:29 UTC, SamuelGSouza commented on pages/team_control/time.md
> +| 11/11/2022 | 0.1    | Criação do plano de organização de tempo da equipe               | Samuel G. / Henrique P.   |
Feito!

2022-11-15 13:21 UTC, ilus1 requested changes

2022-11-15 13:21 UTC, ilus1 commented on _sidebar.md
> -
Precisa fazer merge com a main, e resolver essa parte, não pode apagar o caminho das outras paginas

2022-11-15 13:21 UTC, ilus1 commented on pages/team_control/time.md
> +O presente documento tem por objetivo a documentação do Plano de Tempo.
não sei se "Plano de Tempo" é uma boa expressão, talvez "registro de horários dos membros", "registro de disponibilidade da equipe", "horários para encontro/reunião" ....

2022-11-15 13:21 UTC, ilus1 commented on pages/team_control/time.md
> +O Mapa de Calor é um artefato que permite visualizar a disponibilidade da equipe como um todo, tornando possível otimizar o tempo disponível do time para atividades que exigem execução em conjunto. A
Acho que "otimizar o tempo disponível" não fica legal, o objetivo dessa pagina seria facilitar a organização dos encontros, já que a gente tem essa tabela que só de "bater o olho" a gente pode ver os horários com mais membros disponíveis.

2022-11-15 16:42 UTC, SamuelGSouza commented on _sidebar.md
> -
> Precisa fazer [merge com a main](https://github.com/fga-eps-mds/2022-2-CAPJu-Doc/pull/14#issuecomment-1314005938), e resolver essa parte, não pode apagar o caminho das outras paginas

Eu apaguei esses caminhos quando eu fiz merge com a main, pois alguns estavam duplicados e fora do lugar. Porém, eu apaguei o guia de contribuições sem perceber, mas já corrigi.

Imagem da sidebar que está na main:
![Captura de tela de 2022-11-15 13-27-34](https://user-images.githubusercontent.com/72769279/201976186-d8baf9c1-ea12-4ac3-90be-46a5ca3cd9d9.png)

2022-11-15 19:36 UTC, AntonioAldisio approved these changes

2022-11-15 22:19 UTC, merged