Ajustar a pagina de contribuicao
fga-eps-mds/2022-2-CAPJu-Doc pull request #18
Opened 2022-11-15 13:40 UTC by higton

Ajustar a documentação do guia de contribuição.
Resolve https://github.com/fga-eps-mds/2022-2-CAPJu-Doc/issues/17

2022-11-15 14:04 UTC, ilus1 requested changes

2022-11-15 14:04 UTC, ilus1 commented on pages/contributing/contributing.md
> +| 10/11/2022 | 0.1.0    | Criação do documento              | Paulo Batista |
- Só tem a linha do dia que a pagina subiu, ta faltando a linha que indica esse commit

2022-11-15 19:38 UTC, AntonioAldisio approved these changes

2022-11-15 20:33 UTC, higton commented on pages/contributing/contributing.md
> +| 10/11/2022 | 0.1.0    | Criação do documento              | Paulo Batista |
Done

2022-11-16 00:40 UTC, ilus1 commented
Atualiza com a main antes de dar merge. Só pra garantir que não vai ter rolo.

2022-11-18 00:15 UTC, AntonioAldisio commented
@higton  pode incluir a branch de refactor nas politicas ?

2022-11-19 15:55 UTC, higton commented
Adicionei na documentação.

2022-11-19 19:04 UTC, merged